dist: trusty

language: java

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - jdk: oraclejdk8
    script: mvn -q install
  - jdk: oraclejdk8
    script: mvn -q install -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -Pjetty-test -Dmaven.test.failure.ignore=true

# jetty fails right now on jersey tests, so don't require those tests to pass