dist: trusty

language: java

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - jdk: oraclejdk8
    script: mvn -q install -PWeld2 -Pundertow-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld2 -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld2 -Pjetty-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB -Pundertow-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB -Pjetty-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld3 -Pundertow-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld3 -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld3 -Pjetty-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB2 -Pundertow-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB2 -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB2 -Pjetty-test