dist: trusty

language: java

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - jdk: oraclejdk8
    script: mvn -q install -Dwebserver=undertow
  - jdk: oraclejdk8
    script: mvn -q install -Dwebserver=tomcat
  - jdk: oraclejdk8
    script: mvn -q install -Dwebserver=jetty -Dmaven.test.failure.ignore=true

# jetty fails right now on jersey tests, so don't require those tests to pass