dist: trusty

language: java

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - jdk: oraclejdk8
    script: mvn -q install -PWeld -Pundertow-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld -Pjetty-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB -Pundertow-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -POWB -Pjetty-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld3
  - jdk: oraclejdk8
    script: mvn -q install -PWeld3 -Ptomcat-test
  - jdk: oraclejdk8
    script: mvn -q install -PWeld3 -Pjetty-test